### ISSUE TITLE
项目搭建出错

### ISSUE THREAD

**Issue by keke474** [path-yu/cloud-music#4]
项目虽然飘了很多警告，但是也能运行。可是音乐播放咋没声音嘞，页面也是乱的。难道不是clone到本地，pnmp安装依赖后运行吗？

**Comment by path-yu** [comment]
你有截图吗 我本地跑的都是好好的

**Comment by keke474** [comment]
![image](https://github.com/user-attachments/assets/0ddbf9bc-5bb5-4f49-876b-220620edd4ba)

**Comment by keke474** [comment]
歌词与左侧重叠，感觉这个页面超出了规定的宽度，因为下方存在滚动条。
![image](https://github.com/user-attachments/assets/dd18a597-d859-4832-9c3f-86f60c255edd)

**Comment by keke474** [comment]
请问可以加一下你的联系方式吗？通过issue沟通效率有点低。这是我的邮箱：lxinhui163@163.com；我看到你的主页提供另一个平台链接，但是我注册失败，所以无法通过该平台联系你。

**Comment by path-yu** [comment]
> 歌词与左侧重叠，感觉这个页面超出了规定的宽度，因为下方存在滚动条。
> 
> ![image](https://github.com/user-attachments/assets/dd18a597-d859-4832-9c3f-86f60c255edd)
> 
> 

这个只是没加自适应 我懒得搞

**Comment by path-yu** [comment]
> 请问可以加一下你的联系方式吗？通过issue沟通效率有点低。这是我的邮箱：lxinhui163@163.com；我看到你的主页提供另一个平台链接，但是我注册失败，所以无法通过该平台联系你。

QQ邮箱1974675011 你有什么就问吧

**Comment by path-yu** [comment]
close
