### ISSUE TITLE
white模式显示不正常

### ISSUE THREAD

**Issue by luxinghong** [path-yu/cloud-music#5]
white模式下所有图片均看不见，部分文字显示也有问题

**Comment by path-yu** [comment]
图片显示不出来是网易云服务器问题或者网络问题, 文字部分显示问题我不知道你说的是那个

**Comment by luxinghong** [comment]
sorry，之前没有截图说明。现拉取了最新的代码后，此问题已被解决。

**Comment by path-yu** [comment]
没关系 感谢你的建议, 如果还有其他有问题或者更好的建议, 可以提出, 有空的话我会解决, 也欢迎你可以贡献pr
